language: python
python:
    - "2.7"

install:
    - pip install -r requirements.txt
    - pip install -r test_requirements.txt
    - pip install coveralls

script:
    - python setup.py develop
    - nosetests --with-coverage --cover-package=cloudshell.snmp --where=tests
    - python setup.py sdist --format zip

after_success:
    coveralls
